/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "LiveSkeleton_constants.h"

namespace LiveSkeletonTransfer {

const LiveSkeletonConstants g_LiveSkeleton_constants;

LiveSkeletonConstants::LiveSkeletonConstants() {
}

} // namespace

