/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef LiveSkeleton_CONSTANTS_H
#define LiveSkeleton_CONSTANTS_H

#include "LiveSkeleton_types.h"

namespace LiveSkeletonTransfer {

class LiveSkeletonConstants {
 public:
  LiveSkeletonConstants();

};

extern const LiveSkeletonConstants g_LiveSkeleton_constants;

} // namespace

#endif
